# Build React
FROM node:18-alpine as build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install --production
COPY frontend/ ./
RUN npm run build

# Nginx pour servir le build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Monte les certificats si HTTPS avec Certbot
VOLUME ["/etc/letsencrypt"]

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
